### ISSUE TITLE
Support Weather and location

### ISSUE THREAD

**Issue by jonasbg** [jonasbg/picoblog#32]
Support weather and location from yaml front matter

```yaml
---
weather: Sunny -10C
location: Norway, Trondheim
---
```
